name: TotalComputers
version: 0.9.2b7
description: Computers in vanilla Minecraft
author: JNNGL
website: https://jnngl.com/totalcomputers
main: com.jnngl.totalcomputers.TotalComputers
load: POSTWORLD

commands:
  totalcomputers:
    description: Command for TotalComputers plugin.
    usage: /totalcomputers [...]
    aliases:
      - tcomputers
      - tcmp
permissions:
  totalcomputers.plugin.manage:
    description: Players with this permission can change/reload plugin configuration.
    default: op
  totalcomputers.command.totalcomputers:
    description: Allow access to the /totalcomputers command.
    default: true
  totalcomputers.manage.all:
    description: Players with this permission can create/remove computers without any restrictions.
    default: op
  totalcomputers.manage.crafted:
    description: Players with this permission can manage their computers. Overrides `totalcomputers.selection` permission.
    default: true
  totalcomputers.selection:
    description: Players with this permission can select area.
    default: true
  totalcomputers.use:
    description: Players with this permission can use computers.
    default: true
  totalcomputers.admin:
    description: Players with this permission can use computers as administrator.
    default: op